sudo: required
services:
  - docker 

before_install:
  - docker build -t jovanstojanov/react-test -f ./client/Dockerfile.dev . 

script:
  - docker run jovanstojanov/react-test npm test -- --coverage

after_success:
  - docker build -t jovanstojanov/multi-client -f ./client/Dockerfile .
  - docker build -t jovanstojanov/multi-nginx ./nginx
  - docker build -t jovanstojanov/multi-server ./server 
  - docker build -t jovanstojanov/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jovanstojanov/multi-client
  - docker push jovanstojanov/multi-nginx 
  - docker push jovanstojanov/multi-server 
  - docker push jovanstojanov/multi-worker